-- Ajout des colonnes de quantités pour le Projet 11
IF COL_LENGTH('dbo.WEB_TRAITEMENTS', 'PdtNNC') IS NULL
BEGIN
    ALTER TABLE dbo.WEB_TRAITEMENTS
        ADD PdtNNC INT NOT NULL DEFAULT (0);
END;

IF COL_LENGTH('dbo.WEB_TRAITEMENTS', 'PdtC') IS NULL
BEGIN
    ALTER TABLE dbo.WEB_TRAITEMENTS
        ADD PdtC INT NOT NULL DEFAULT (0);
END;

IF COL_LENGTH('dbo.WEB_TRAITEMENTS', 'PdtANC') IS NULL
BEGIN
    ALTER TABLE dbo.WEB_TRAITEMENTS
        ADD PdtANC INT NOT NULL DEFAULT (0);
END;

UPDATE dbo.WEB_TRAITEMENTS
SET PdtNNC = ISNULL(PdtNNC, 0),
    PdtC = ISNULL(PdtC, 0),
    PdtANC = ISNULL(PdtANC, 0);

